### ISSUE TITLE
Kotlin register Plugins

### ISSUE THREAD

**Issue by joe69** [ZebraDevs/DataWedge-Flutter-Demo#1]
Hi, 

my problem when i install a plugin (example Cloud Firestore) the plugin is not working/found in the flutter part. 

Thanks,
Thomas

**Comment by darryncampbell** [comment]
Hi, is that specific to this project?  This project is not doing anything special with plugins.

**Comment by joe69** [comment]
No i want to take your demo and extend it for me. I want only add cloud firestore and save the scan code to the database. 
Maybe you have a solution for me , how i can use flutter plugins.
When i comment out the koltin code , the plugins works. 

`E/flutter (16977): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method DocumentReference#setData on channel plugins.flutter.io/cloud_firestore)
E/flutter (16977): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (16977): <asynchronous suspension>
E/flutter (16977): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (16977): #2      DocumentReference.setData (package:cloud_firestore/src/document_reference.dart:51:30)
E/flutter (16977): #3      _MyHomePageState.build (package:datawedgeflutter/main.dart:108:55)
E/flutter (16977): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
E/flutter (16977): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
E/flutter (16977): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter (16977): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter (16977): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (16977): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter (16977): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter (16977): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter (16977): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter (16977): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter (16977): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (16977): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter (16977): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter (16977): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter (16977): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter (16977): #29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter (16977): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter (16977): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (16977): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter (16977): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter (16977): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter (16977): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter (16977): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (16977): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (16977): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter (16977): #43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)`

**Comment by darryncampbell** [comment]
I am not a Flutter expert I am afraid and this looks like a configuration issue of the cloud_firestore plugin...  My guess would be to add cloud_firestore to the pubspec.yaml file and then re-run the `flutter run` process based on https://pub.dev/packages/cloud_firestore#-readme-tab- and https://github.com/flutter/flutter/issues/10912 but that's just a guess.

**Comment by joe69** [comment]
ok in the MainActivity you miss to load all other Plugins:

import io.flutter.plugins.GeneratedPluginRegistrant;

 override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);

Thanks Thomas
