### ISSUE TITLE
Can i use Zebra DataWedge on a non-Zebra android device?

### ISSUE THREAD

**Issue by Ezequiel-Larena** [ZebraDevs/DataWedge-Flutter-Demo#10]
I need to develop an Android application that should receive barcode and RFID scans from the Zebra RFD8500 reader. I don't have an Android Zebra device, just a regular Android.

Can i use DataWedge with this setup?

If not, should i use the Zebra Scanner SDK to get the barcodes and the Zebra RFID SDK to get the RFID reads? Does the Zebra RFID SDK works on non-Zebra Android devices?

**Comment by darryncampbell** [comment]
Hi, you cannot use DataWedge with RFD8500 as it is not yet supported.  To read RFID tags with the RFD8500 on non-Zebra Android devices you should use the https://www.zebra.com/us/en/support-downloads/software/developer-tools/zebra-rfid-xamarin-sdk-and-demoapp-for-android.html API.  To scan barcodes with the RFD8500 you should use https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-android.html.  The demo application included in one of those SDKs is called 'scan scan read', *I think*, and should show both being used from the same app.

**Comment by Ezequiel-Larena** [comment]
I can't find that demo app that implements both RFID and barcode. You could give it to me?
On the other hand, is it possible that two Sdk of different languages ​​coexist in the same application?
Thanks!

**Comment by darryncampbell** [comment]
Sorry, I gave the wrong link for the Android RFID SDK, please see here: https://www.zebra.com/us/en/support-downloads/software/developer-tools/rfid-sdk-for-android.html

**Comment by Ezequiel-Larena** [comment]
Ok! Thanks you!

**Comment by martinmateossanchez** [comment]
Hello! Opening this thread again, I have a [SEYPOS ScanMax D22](https://www.seypos.com/en/industrial-pda/seypos-scanmax-d22/) which has a 1D/2D Zebra Barcode Scanner SE4710. All the information I've found so far is for developing either on Zebra devices or external Zebra scans connected via cable or bluettoth to a non-Zebra Android device. Which development tool do I have to use to connect to the embedded Zebra scanner in my device? Thank you so much in advance.

**Comment by darryncampbell** [comment]
@marmatsan you would need to get an SDK from SEYPOS.  Datawedge will only work on non-Zebra devices.
