### ISSUE TITLE
RFID mode

### ISSUE THREAD

**Issue by datttran** [ZebraDevs/DataWedge-Flutter-Demo#13]
Hi, I am using this on MC3300. Is there a way for me to switch between the RFID mode and barcode mode?

**Comment by datttran** [comment]
I have noticed that when scanning over an RFID tag, the light on the scanner lighted up. So I am not sure if this is an issue with the mode switch or if I need a different way to display the RFID scan.

**Comment by darryncampbell** [comment]
It should work but I do not have the hardware to test it.  You would need to modify https://github.com/ZebraDevs/DataWedge-Flutter-Demo/blob/master/datawedge_flutter/android/app/src/main/kotlin/com/darryncampbell/datawedgeflutter/MainActivity.kt#L88 to enable the RFID plugin and also modify https://github.com/ZebraDevs/DataWedge-Flutter-Demo/blob/master/datawedge_flutter/android/app/src/main/kotlin/com/darryncampbell/datawedgeflutter/MainActivity.kt#L74 to reflect the format of the received Intent

**Comment by datttran** [comment]
It works. Only need to enable the RFID plugin. Thank you so much.

**Comment by ijpe** [comment]
@datttran @darryncampbell 
Do you have a example code works?, i don't receive any error or crash but the tags are not readed, and not is possible read tags with the dock connected for debug.
