### ISSUE TITLE
Modify RFID hardware key since createDataWedgeProfile

### ISSUE THREAD

**Issue by ijpe** [ZebraDevs/DataWedge-Flutter-Demo#15]
Is possible change the Default value, for the RFID Hardware Key on Datawedge profile?

**Comment by darryncampbell** [comment]
You should be able to use the StageNow tool (https://www.zebra.com/us/en/support-downloads/software/utilities/stagenow.html) and invoke the KeyMappingManager (https://techdocs.zebra.com/mx/keymappingmgr/) to remap the SCAN or TRIGGER buttons (exact key will depend on your device) to some other key.
