### ISSUE TITLE
Is there away to get the RSSI value?, of some rfid tag scanned

### ISSUE THREAD

**Issue by ijpe** [ZebraDevs/DataWedge-Flutter-Demo#16]
I need get the **RSSI** value, on my flutter app, but i only receive scanData and symbology for each scanned tag.

**Comment by darryncampbell** [comment]
I'm looking at the documentation at:

- https://techdocs.zebra.com/datawedge/11-2/guide/input/rfid/
- https://techdocs.zebra.com/datawedge/11-2/guide/output/intent/

And I do not see anything.  There should be an RWDemo on your device, does that output the RSSI value?
Apologies but I do not have hardware to test with.

**Comment by ijpe** [comment]
@darryncampbell no, the RWDemo only print the RFID code on screen, the **123RFID Mobile** of Zebra, print the code and the RSSI value.

**Screenshot**
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK4dD41_vFeVfddzEit2hbxaY0iFrnLUuLVfRHUeQ9UUTkiNN4civbrobSS4iwsA6dIYs&usqp=CAU

**123RFID Mobile**
https://www.zebra.com/us/en/support-downloads/software/demo/123rfid-mobile.html

**Comment by darryncampbell** [comment]
Thanks for the info, let me ask internally and get back to you

**Comment by darryncampbell** [comment]
@ijpe apologies for the delayed response but I have been away.  I checked internally and the RSSI value for a particular tag is not available.  The Post filter (introduced in DW 7.4) can be used to filter out tags according to RSSI value, https://techdocs.zebra.com/datawedge/11-2/guide/input/rfid/

**Comment by ijpe** [comment]
@darryncampbell  Is planned introduce this value on the future?

**Comment by darryncampbell** [comment]
Do you have an account manager at Zebra?  The reason I ask is that it would get higher priority if you went through that route.

**Comment by ijpe** [comment]
I think that the company have one so i ask internally, thank you
