### ISSUE TITLE
MissingPluginException according to custom MainActivity.kt

### ISSUE THREAD

**Issue by iksivee** [ZebraDevs/DataWedge-Flutter-Demo#3]
Custom code in MainActivity.kt results in plugin errors. Like barcode_scan, sqflite plugin or path_provider. When I delete the code inside MainActivity(), it works. Any idea how to solve it? 

Error messages be like: 
MissingPluginException(No implementation found for method requestCameraPermission on channel de.mintware.barcode_scan)

**Comment by darryncampbell** [comment]
This sounds very similar to https://github.com/ZebraDevs/DataWedge-Flutter-Demo/issues/1 which should have been fixed by https://github.com/ZebraDevs/DataWedge-Flutter-Demo/commit/e5b36e0d5fded1668e529f26793def7f01151a89.  

Is this the same issue?

**Comment by iksivee** [comment]
Thanks for your help, finally this solved the issue.

I was trying this but with deleting "<meta-data android:name="flutterEmbedding" android:value="2" />" in AndroidManifest.

**Comment by darryncampbell** [comment]
Great.  Closing but please reopen if you disagree.
