### ISSUE TITLE
 communication problems between APP and DataWedge

### ISSUE THREAD

**Issue by alelav79** [ZebraDevs/DataWedge-Flutter-Demo#4]
Hello,

I have this problem :

Restarted application in 2.991ms.

[38;5;248m════════ Exception caught by services library ══════════════════════════════════[39;49m
[38;5;244mThe following MissingPluginException was thrown while activating platform stream on channel com.example.bacode_scanner_zebra/scan:[39;49m
MissingPluginException(No implementation found for method listen on channel com.example.bacode_scanner_zebra/scan)

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#1      EventChannel.receiveBroadcastStream.<anonymous closure>[39;49m
 package:flutter/…/services/platform_channel.dart
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
E/flutter ( 8996): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method createDataWedgeProfile on channel com.example.bacode_scanner_zebra/command)
[38;5;244mE/flutter ( 8996): #0      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter ( 8996): <asynchronous suspension>
[38;5;248mE/flutter ( 8996): #1      _MyHomePageState._createProfile[39;49m
 package:bacode_scanner_zebra/main.dart
E/flutter ( 8996): <asynchronous suspension>
E/flutter ( 8996):
I/flutter ( 8996): TAP
I/flutter ( 8996): UNTAP
E/flutter ( 8996): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method sendDataWedgeCommandStringParameter on channel com.example.bacode_scanner_zebra/command)
[38;5;244mE/flutter ( 8996): #0      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter ( 8996): <asynchronous suspension>
[38;5;248mE/flutter ( 8996): #1      _MyHomePageState._sendDataWedgeCommand[39;49m
 package:bacode_scanner_zebra/main.dart
E/flutter ( 8996): <asynchronous suspension>
E/flutter ( 8996):
E/flutter ( 8996): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method sendDataWedgeCommandStringParameter on channel com.example.bacode_scanner_zebra/command)
[38;5;244mE/flutter ( 8996): #0      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter ( 8996): <asynchronous suspension>
[38;5;248mE/flutter ( 8996): #1      _MyHomePageState._sendDataWedgeCommand[39;49m
 package:bacode_scanner_zebra/main.dart
E/flutter ( 8996): <asynchronous suspension>
E/flutter ( 8996):

**Comment by dancamdev** [comment]
`MissingPluginException(No implementation found for method listen on channel com.example.bacode_scanner_zebra/scan)`

please, do you mind double checking your package name and eventually share the `MainActivity.kt` and the dart file where you have the method and event channels names declared?

**Comment by acassar** [comment]
Hello,

I have a similar problem here, but I don't know if it's directly related. When I try implementing the kotlin code (basically copying the 3 files to my project), I have a MissingPluginException on any plugin I try to use and described in pubspec.yml.

**Comment by darryncampbell** [comment]
I never merged https://github.com/ZebraDevs/DataWedge-Flutter-Demo/pull/2 which fixed https://github.com/ZebraDevs/DataWedge-Flutter-Demo/issues/1.  That was likely an oversight.  I will merge it now.  Does that solve your issue?

**Comment by acassar** [comment]
Fixed for me ! thanks

**Comment by alelav79** [comment]
> MainActivity.kt

`package com.example.bacode_scanner_zebra

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
`

main.dart

`import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DataWedge Flutter',
      theme: ThemeData(
        primarySwatch: Colors.orange,
      ),
      home: MyHomePage(title: 'DataWedge Flutter'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const MethodChannel methodChannel =
      MethodChannel('com.example.bacode_scanner_zebra/command');
  static const EventChannel scanChannel =
      EventChannel('com.example.bacode_scanner_zebra/scan');

  //  This example implementation is based on the sample implementation at
  //  https://github.com/flutter/flutter/blob/master/examples/platform_channel/lib/main.dart
  //  That sample implementation also includes how to return data from the method
  Future<void> _sendDataWedgeCommand(String command, String parameter) async {
    try {
      String argumentAsJson = "{\"command\":$command,\"parameter\":$parameter}";
      await methodChannel.invokeMethod(
          'sendDataWedgeCommandStringParameter', argumentAsJson);
    } on PlatformException {
      //  Error invoking Android method
    }
  }

  Future<void> _createProfile(String profileName) async {
    try {
      await methodChannel.invokeMethod('createDataWedgeProfile', profileName);
    } on PlatformException {
      //  Error invoking Android method
    }
  }

  String _barcodeString = "Barcode will be shown here";
  String _barcodeSymbology = "Symbology will be shown here";
  String _scanTime = "Scan Time will be shown here";

  @override
  void initState() {
    super.initState();
    scanChannel.receiveBroadcastStream().listen(_onEvent, onError: _onError);
    _createProfile("DataWedgeFlutterDemo");
  }

  void _onEvent(Object event) {
    setState(() {
      Map barcodeScan = jsonDecode(event);
      _barcodeString = "Barcode: " + barcodeScan['scanData'];
      _barcodeSymbology = "Symbology: " + barcodeScan['symbology'];
      _scanTime = "At: " + barcodeScan['dateTime'];
    });
  }

  void _onError(Object error) {
    setState(() {
      _barcodeString = "Barcode: error";
      _barcodeSymbology = "Symbology: error";
      _scanTime = "At: error";
    });
  }

  void startScan() {
    setState(() {
      _sendDataWedgeCommand(
          "com.symbol.datawedge.api.SOFT_SCAN_TRIGGER", "START_SCANNING");
    });
  }

  void stopScan() {
    setState(() {
      _sendDataWedgeCommand(
          "com.symbol.datawedge.api.SOFT_SCAN_TRIGGER", "STOP_SCANNING");
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("DataWedge Flutter"),
      ),
      body: Container(
          child: Row(children: [
        Expanded(
          child: Column(
            children: [
              Container(
                padding: const EdgeInsets.all(32),
                child: Row(
                  children: [
                    Expanded(
                      /*1*/
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          /*2*/
                          Container(
                            padding: const EdgeInsets.only(bottom: 8),
                            child: Text(
                              '$_barcodeString',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          Container(
                            padding: const EdgeInsets.only(bottom: 8),
                            child: Text(
                              '$_barcodeSymbology',
                              style: TextStyle(
                                color: Colors.grey[500],
                              ),
                            ),
                          ),
                          Text(
                            '$_scanTime',
                            style: TextStyle(
                              color: Colors.deepPurple,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              GestureDetector(
                // When the child is tapped, show a snackbar.
                onTapDown: (TapDownDetails) {
                  //startScan();
                  startScan();
                  print("TAP");
                },
                onTapUp: (TapUpDetails) {
                  stopScan();
                  print("UNTAP");
                },
                // The custom button
                child: Container(
                    margin: EdgeInsets.all(8.0),
                    padding: EdgeInsets.all(22.0),
                    decoration: BoxDecoration(
                      color: Colors.blue,
                      borderRadius: BorderRadius.circular(8.0),
                    ),
                    child: Column(
                      children: [
                        Center(
                          child: Text(
                            "SCAN",
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                        /*Center(
                          child: ElevatedButton(
                            child: Text('Launch screen'),
                            onPressed: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => IrTest()),
                              );
                            },
                          ),
                        )*/
                      ],
                    )),
              ),
            ],
          ),
        ),
      ])),
    );
  }
}
`

**Comment by alelav79** [comment]
Fixed ! Thanks !

I had forgotten the files

Scan.kt
MainActivity.kt
DWInterface.kt

in 

\bacode_scanner_zebra\android\app\src\main\kotlin\com\example\bacode_scanner_zebra

I renamed 

com.darryncampbell.datawedgeflutter

in

com.example.bacode_scanner_zebra
