### ISSUE TITLE
How to emulate scan event with ADB?

### ISSUE THREAD

**Issue by sabit** [ZebraDevs/DataWedge-Flutter-Demo#9]
I am trying to send emulated scan event to the app running under Android Emulator. I am following [this guide](https://developer.zebra.com/blog/test-your-zebra-scanning-application-emulator). What should be the service name in place of _com.zebra.dwapiexerciser.ACTION_?

**Comment by sabit** [comment]
` adb  shell am broadcast -a com.darryncampbell.datawedgeflutter.SCAN  -e  com.symbol.datawedge.data_string 9781846683817 -e com.symbol.datawedge.source scanner -e com.symbol.datawedge.label_type LABEL_TYPE_EAN13`

**Comment by darryncampbell** [comment]
Whatever is specified at https://github.com/ZebraDevs/DataWedge-Flutter-Demo/blob/master/datawedge_flutter/android/app/src/main/kotlin/com/darryncampbell/datawedgeflutter/MainActivity.kt#L114

In the case of this demo, it would be `com.darryncampbell.datawedgeflutter.SCAN`

You closed this issue 29 seconds ago but I have already written the above so I am going to comment anyway :)
